# Generated by Django 3.0.2 on 2020-01-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200103_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='parametros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precohora', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mensalidade', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
    ]
