# Generated by Django 3.0.2 on 2020-01-03 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_parametros'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='parametros',
            new_name='parametro',
        ),
    ]
