# Generated by Django 3.0.2 on 2020-01-03 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_movimentorotativo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentorotativo',
            name='saida',
            field=models.DateTimeField(null=True),
        ),
    ]
