# Generated by Django 3.0.2 on 2020-01-03 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200103_1107'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovimentoRotativo',
            new_name='movimento_rotativo',
        ),
    ]
