# Generated by Django 3.0.2 on 2020-01-03 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200103_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='mensalista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateField()),
                ('mensalidade', models.DecimalField(decimal_places=2, max_digits=7)),
                ('veiculo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.veiculo')),
            ],
        ),
    ]
